### ISSUE TITLE
given a retrieved webACL file, add a webid to it

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_acl#3]
requires #2

after creating the appropriate object(s) representing the webACL per #2

- [ ] function to add a webID to the ACL object(s) (webID as an arg) with indicated permissions (as args) (#20, #22)
- [ ] serialize webACL graph to string (#24)
- [ ] ~~function to write ACL object(s) to a file~~ (no need for file, can do as string)
- [ ] function to POST the ACL to a specific "group" BasicContainer one level down from the server BaseConatiner. (#25)

**Comment by ndushay** [comment]
this is now ticketed in more atomic issues, so closing this one.
