### ISSUE TITLE
server migration script for uber containers, assoc webACL locked down appropriately

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_acl#30]
requires #33

The idea is for an easy way to spin up a docker image with sinopia specific LDP/trellis configuration.  We essentially need this every time we want a server:  
- dev server put anew on AWS;  
- temporary servers used for integration test code;  
- temporary servers used for code development
- spinning up production trellis for sinopia server after terraform infra rebuild (this is a special case, and we will also want to get our data back from RDS, etc.)

This would be useful for the developers, and would also make integration testing a lot easier for all the code bases that talk to the sinopia server:
- sinopia_editor
- sinopia_acl
- sinopia_profile_editor
- sinopia_server dev
- sinopia_client ? (generated swagger client)

We think it’s not possible to create a docker image with this, not least because of webID instability.  So we're thinking a migration script would be useful.

### What would be in the migration?

DEFINITELY these:
- [ ] #28 root container webACL needs to be locked down to admin-only control, write;  world readable
- [ ] #28 repository container needs to be created, and needs analogous locked down webACL
- [ ] #19 test root container webACL changed to write/control for admin user only
- [ ] #28 /repository/ld4p group with webACL: admin-only control;  dev users write; world readable

POSSIBLY these:
    - ~~latest resourceTemplates from sinopia_sample_profiles loaded into appropriate containers (or at least some of them)~~ the current plan is for this to happen manually
- if devs aren't all admin users, then remaining devs get write permission on any new containers
- ~~other sinopia-always-will-have group containers~~ current plan is for admin to create group containers, other than ld4p
- possibly a developer-testing group container
- [ ] ~~#23 test group container webACL ~~

AND:
- [ ] ~~#25 way to POST.  Basic auth okay for now.  See #5 for JWT and cognito access tokens.~~  See #33.

Dealing with webACLs means dealing with webids.  Dealing with webids means dealing with the possibility that cognito will, at times, need to regen the webids from the user names.  See #29.

**Comment by ndushay** [comment]
do this with basic auth for now;  using Cognito, JWT, and access tokens is in #5

**Comment by ndushay** [comment]
@mjgiarlo I believe this is now done?

**Comment by mjgiarlo** [comment]
@ndushay done-zo. closing!
