### ISSUE TITLE
http plumbing w cognito

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_acl#33]
This uber ticket comprises:
- [ ] #26 http GET from server (in sinopia_acl case, we will GET WAC for containers)
- [x] #5 get valid accessToken for user email/password
- [x] #25 POST WAC to server

this ticket does NOT include either of these concerns:
- #29 (given user email, get webid)
- deal with webids changing due to cognito pool changes

**Comment by ndushay** [comment]
I'm closing this due to ACL work changing shape.  Currently working on #29
